name: Node.js CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x # updated from LTS to specific version for consistency
        uses: actions/setup-node@v3
        with:
          node-version: 18.x # sets Node version to 18.x for stable installs
          cache: 'npm'
      - run: npm install
      - run: npm test
